### PR TITLE
Add new Testing Tools

### PR DESCRIPTION
**Pull request by Hiro-Nakamura**
Adding 2 new features for enhancing our ability to debug our failed e2e tests.  

New Route `get /versionCheck` will return (and print to console) the current versions of all our running services

New Route `POST /testlog` will insert a bold `log` statement into the running console logs being generated by the system.  This is handy for each of our e2e tests to begin by marking a log, so we can see all the activity generated by a specific test.

NOTE: this release depends on PR : [Create a default version check handler #67](https://github.com/digi-serve/ab-utils/pull/67)
## Release Notes

- [wip] Add new versionCheck and testLog features

### CODE REVIEW

**Review by guyyoo — APPROVED** [review]
LGTM!

**Review by nh758 — CHANGES_REQUESTED** [review]
The code itself looks fine, but I don't understand why these are written as `hooks` instead of `controllers`?

If it's to skip our default policies, we can add exceptions in the `config/policies.js`

**Comment by Hiro-Nakamura** [comment]
Mostly the choice to implement a hook rather than a controller action was due to it following the same pattern as the existing `/healthcheck` hook.  Since it was just a refactor of that, I decided to keep it as a hook.

not much difference really.

**Comment by Hiro-Nakamura** [comment]
OK, It's been 4 days since my response.  I'm going to assume we good to go with this.

**Pull request merged**
